In [22]:
import pandas as pd

from output import *
from plots import *
%load_ext autoreload
%autoreload 2

%pylab

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib

In [5]:
rr = 'zubehoer/ref_red5e9.dat_J31_11220'
rr = read_ref_red(rr)
rr.describe()

,n,t,mCore,menv,m,L,Lcomp,mdotcore,mdotgasl,rcore,...,109,110,111,112,113,114,115,systemNo,planetNo,NoEmbryos
count,11220.000000,1.122000e+04,11220.000000,11220.000000,11220.000000,1.122000e+04,1.122000e+04,1.122000e+04,1.122000e+04,11220.000000,...,11220.000000,11220.000000,1.122000e+04,11220.000000,11220.000000,1.122000e+04,11220.000000,11220.000000,11220.000000,11220.000000
mean,8098.534061,5.000000e+09,3.155263,68.445787,71.601028,4.436733e+03,4.436733e+03,3.841785e-07,6.866261e-06,0.089517,...,0.020988,117.941549,9.000000e-01,48.223908,6.052024,1.258486e-07,0.180109,281.000000,10.500000,19.964349
std,9746.754395,0.000000e+00,9.425533,528.005096,532.680964,1.889578e+05,1.889578e+05,1.062668e-05,4.859522e-04,0.041441,...,0.011238,35.323213,1.901897e-13,30.530965,9.197094,9.766056e-08,0.232014,161.953711,5.766538,0.843685
min,0.000000,5.000000e+09,0.000100,0.000000,0.000100,0.000000e+00,0.000000e+00,0.000000e+00,-1.808620e-05,0.003499,...,0.004717,69.861100,9.000000e-01,15.527300,0.060003,4.340780e-08,0.000000,1.000000,1.000000,0.000000
25%,234.180000,5.000000e+09,0.206147,0.000000,0.206238,1.191938e-05,1.191938e-05,0.000000e+00,-4.122110e-16,0.058056,...,0.012830,89.035400,9.000000e-01,25.220300,0.293022,7.630440e-08,0.000000,141.000000,5.750000,20.000000
50%,4309.365000,5.000000e+09,0.523508,0.000139,0.525041,4.170970e-05,4.170970e-05,0.000000e+00,0.000000e+00,0.075174,...,0.018152,109.347000,9.000000e-01,38.040100,1.491810,1.003390e-07,0.000000,281.000000,10.500000,20.000000
75%,11287.000000,5.000000e+09,1.781538,0.010874,1.845990,1.000000e-03,1.000000e-03,0.000000e+00,0.000000e+00,0.108368,...,0.026555,138.062000,9.000000e-01,60.642500,7.600465,1.424190e-07,0.433896,421.000000,15.250000,20.000000
max,49722.100000,5.000000e+09,211.937000,16994.700000,17029.600000,1.909940e+07,1.909940e+07,8.278210e-04,4.386110e-02,0.332243,...,0.079642,219.567000,9.000000e-01,153.377000,40.000000,1.181050e-06,0.569156,561.000000,20.000000,20.000000

In [63]:
np.linspace(1,100,100)

array([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
         10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,
         19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,
         37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,   45.,
         46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,   54.,
         55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,
         64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,   72.,
         73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.,
         82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
         91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,  100.])

In [64]:
lognorm = np.random.lognormal(size=100)

In [74]:
# try some well-defined test data
df = pd.DataFrame({'a':np.linspace(1,100,100), 'r':np.linspace(100,10000,100)})
df.describe()

                a             r
count  100.000000    100.000000
mean    50.500000   5050.000000
std     29.011492   2901.149198
min      1.000000    100.000000
25%     25.750000   2575.000000
50%     50.500000   5050.000000
75%     75.250000   7525.000000
max    100.000000  10000.000000

In [75]:
df.r.hist()

In [85]:
plot_occurrence(rr, cmap='YlGn')

using only planets with status "0"

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 array([  1.00000000e-03,   1.26485522e-03,   1.59985872e-03,
          2.02358965e-03,   2.55954792e-03,   3.23745754e-03,
          4.09491506e-03,   5.17947468e-03,   6.55128557e-03,
          8.28642773e-03,   1.04811313e-02,   1.32571137e-02,
          1.67683294e-02,   2.12095089e-02,   2.68269580e-02,
          3.39322177e-02,   4.29193426e-02,   5.42867544e-02,
          6.86648845e-02,   8.68511374e-02,   1.09854114e-01,
          1.38949549e-01,   1.75751062e-01,   2.22299648e-01,
          2.81176870e-01,   3.55648031e-01,   4.49843267e-01,
          5.68986603e-01,   7.19685673e-01,   9.10298178e-01,
          1.15139540e+00,   1.45634848e+00,   1.84206997e+00,
          2.32995181e+00,   2.94705170e+00,   3.72759372e+00,
          4.71486636e+00,   5.96362332e+00,   7.54312006e+00,
          9.54095476e+00,   1.20679264e+01,   1.52641797e+01,
          1.93069773e+01,   2.44205309e+01,   3.08884360e+01,
          3.90693994e+01,   4.94171336e+01,   6.25055193e+01,
          7.90604321e+01,   1.00000000e+02]),
 array([  1.00000000e-03,   1.20679264e-03,   1.45634848e-03,
          1.75751062e-03,   2.12095089e-03,   2.55954792e-03,
          3.08884360e-03,   3.72759372e-03,   4.49843267e-03,
          5.42867544e-03,   6.55128557e-03,   7.90604321e-03,
          9.54095476e-03,   1.15139540e-02,   1.38949549e-02,
          1.67683294e-02,   2.02358965e-02,   2.44205309e-02,
          2.94705170e-02,   3.55648031e-02,   4.29193426e-02,
          5.17947468e-02,   6.25055193e-02,   7.54312006e-02,
          9.10298178e-02,   1.09854114e-01,   1.32571137e-01,
          1.59985872e-01,   1.93069773e-01,   2.32995181e-01,
          2.81176870e-01,   3.39322177e-01,   4.09491506e-01,
          4.94171336e-01,   5.96362332e-01,   7.19685673e-01,
          8.68511374e-01,   1.04811313e+00,   1.26485522e+00,
          1.52641797e+00,   1.84206997e+00,   2.22299648e+00,
          2.68269580e+00,   3.23745754e+00,   3.90693994e+00,
          4.71486636e+00,   5.68986603e+00,   6.86648845e+00,
          8.28642773e+00,   1.00000000e+01]),
 <matplotlib.axes._subplots.AxesSubplot at 0x7f86c1f0d7b8>)

In [80]:
cb=fig.colorbar?

In [ ]:
cb=fig.colorbar